- Real:
    low: -6.
    high: 6.
    name: 'dx_0'
- Real:
    low: -6.
    high: 6.
    name: 'dy_0'
- Real:
    low: -6.
    high: 6.
    name: 'dz_0'
- Real:
    low: -6.
    high: 6.
    name: 'dthx_0'
- Real:
    low: -6.
    high: 6.
    name: 'dthy_0'
- Real:
    low: -6.
    high: 6.
    name: 'dthz_0'