- Real:
    low: -4.
    high: 4.
    name: 'dx_401'
- Real:
    low: -4.
    high: 4.
    name: 'dy_401'
- Real:
    low: -4.
    high: 4.
    name: 'dz_401'
- Real:
    low: -4.
    high: 4.
    name: 'dthx_401'
- Real:
    low: -4.
    high: 4.
    name: 'dthy_401'
- Real:
    low: -4.
    high: 4.
    name: 'dthz_401'