- Real:
    low: -6.
    high: 6.
    name: 'dx_401'
- Real:
    low: -6.
    high: 6.
    name: 'dy_401'
- Real:
    low: -6.
    high: 6.
    name: 'dz_401'
- Real:
    low: -6.
    high: 6.
    name: 'dthx_401'
- Real:
    low: -6.
    high: 6.
    name: 'dthy_401'
- Real:
    low: -6.
    high: 6.
    name: 'dthz_401'