io-services:
  reader:
    class: org.jlab.clas.std.services.convertors.HipoToHipoReader
    name: HipoToHipoReader
  writer:
    class: org.jlab.clas.std.services.convertors.HipoToHipoWriter
    name: HipoToHipoWriter
services:
  - class: org.jlab.clas.swimtools.MagFieldsEngine
    name: MAGFIELDS
  - class: org.jlab.rec.rich.RICHEBEngine
    name: RICH
configuration:
  io-services:
    writer:
      compression: 2
      #schema_dir: /work/clas12/users/devita/clas12validation/clara-iss643-rich/plugins/clas12/etc/bankdefs/hipo4/singles/dst
      schema_dir: /home/unico/oldversion/coatjava/etc/bankdefs/hipo4/singles/dst
  services:
    MAGFIELDS:
      magfieldSolenoidMap: Symm_solenoid_r601_phi1_z1201_13June2018.dat
      magfieldTorusMap: Full_torus_r251_phi181_z251_08May2018.dat
      variation: rga_fall2018
    RICH:
      variation: scan_variation_2
#      timestamp: 03/01/2021-20:00:00

mime-types:
  - binary/data-hipo
