- Real:
    low: -6.
    high: 6.
    name: 'dx_401'
- Real:
    low: -6.
    high: 6.
    name: 'dy_401'
- Real:
    low: -6.
    high: 6.
    name: 'dthz_401'
- Real:
    low: -6.
    high: 6.
    name: 'dx_202'
- Real:
    low: -6.
    high: 6.
    name: 'dy_202'
- Real:
    low: -6.
    high: 6.
    name: 'dthz_202'
